name: Release

on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+*" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Get the version
        id: get_version
        run: |
          version=$(echo ${GITHUB_REF/refs\/tags\//} | cut -c 2-)
          echo ::set-output name=VERSION::$version
        shell: bash
      - run: make assembly
      
      - name: Generate checksums (Release prep)
        run: |
             cd app/target/scala-2.13/
             sha256sum "luyu-chain33-${{ steps.get_version.outputs.VERSION }}.jar" > "luyu-chain33-${{ steps.get_version.outputs.VERSION }}.jar.checksum"
             cd ../../../wallet/target/scala-2.13/

      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
